name: Ubuntu image build
on:
  workflow_dispatch:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: noble
        type: string
  workflow_call:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: noble
        type: string

# variables path are inconsistent when triggering with workflow_dispatch
# or workflow_call.
jobs:
  build:

    strategy:
      matrix:
        arch:
          - name: 'amd64'
            os: ubuntu-24.04
            mirror: http://azure.archive.ubuntu.com/ubuntu
    environment: secrets
    runs-on: ${{ matrix.arch.os }}
    env:
      SERIES: ${{ github.event.inputs.series || inputs.series }}
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: update APT cache
        run: sudo apt-get update
      - name: installing dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
                qemu-utils \
                debootstrap \
                s3cmd
      - name: installing genesis
        run: sudo python3 -m pip install git+https://github.com/gjolly/genesis.git@main
      - name: running debootstrap
        run: sudo genesis debootstrap --output ./rootfs --series $SERIES --mirror "${{ matrix.arch.mirror }}"
      - name: creating disk-image
        run: sudo genesis create-disk --size 4 --rootfs-dir ./rootfs
      - name: Updating the system
        run: |
          sudo genesis update-system \
            --disk-image disk.img \
            --mirror "${{ matrix.arch.mirror }}" \
            --series "$SERIES" \
            --extra-package vim \
            --extra-package ca-certificates \
            --extra-package openssh-server \
            --extra-package cloud-init \
            --extra-package curl \
            --extra-package btop \
            --extra-package linux-generic
      - name: Install Grub
        run: |
          sudo genesis install-grub --disk-image disk.img
      - name: Converting to qcow2
        run: |
          sudo qemu-img convert -f raw -O qcow2 disk.img disk.qcow2
      - name: Upload to Scaleway
        run: |
          s3cmd \
            --ssl \
            --bucket-location='fr-par' \
            --host='s3.fr-par.scw.cloud' \
            --host-bucket='%(bucket)s.s3.fr-par.scw.cloud' \
            --access_key ${{ secrets.S3_ACCESS_KEY }} \
            --secret_key ${{ secrets.S3_SECRET_KEY }} \
              put file ./disk.qcow2 "s3://gjolly-images/ubuntu-${SERIES}-$(date +%Y%m%d).qcow2"
